update_interval: 1000

theme: "default"

layout:
    show_cpu: true
    show_memory: true
    show_network: true
    show_disk: true
    show_process_details: true

sort_by: "cpu"

filters:

custom_theme:
    background: "black"
    foreground: "white"
    header: "cyan"
    cpu_low: "green"
    cpu_medium: "yellow"
    cpu_high: "red"
    memory_low: "green"
    memory_medium: "yellow"
    memory_high: "red"
    disk_low: "green"
    disk_medium: "yellow"
    disk_high: "red"
    network_rx: "blue"
    network_tx: "magenta"
    process_selected: "cyan"
    border: "gray"
    tab_active: "cyan"
    tab_inactive: "gray"
